# fly.toml app configuration file generated for teki-api on 2026-03-09T12:42:40+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'teki-api'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[deploy]
  release_command = "bin/rails db:migrate"
  strategy = "immediate"

[env]
  RAILS_ENV = 'production'
  RAILS_LOG_TO_STDOUT = 'true'
  RAILS_MAX_THREADS = '5'
  RAILS_SERVE_STATIC_FILES = 'true'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'suspend'   # 'suspend' resumes faster than 'stop'
  auto_start_machines = true
  min_machines_running = 1         # keeps at least 1 machine always up
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 250
    soft_limit = 200

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'