# PostgreSQL. Versions 9.5 and up are supported.
#
# Install the PostgreSQL driver
#   gem install pg
#
# Ensure the pg gem is defined in your Gemfile
#   gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>
  host: <%= ENV.fetch('DB_HOST') { 'localhost' } %>
  port: <%= ENV.fetch('DB_PORT') { 5432 } %>

development:
  <<: *default
  database: <%= ENV['DB_DEV'] %>

test:
  <<: *default
  database: <%= ENV['DB_TEST'] %>

DATABASE_URL: <%= ENV['DATABASE_URL'] %>

production:
  <<: *default
  database: <%= ENV['DB_PROD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
